// ============================================================
// CURSES — 110 curses from mild to severe
// Used by the Curse Wheel. Exported as a global for rwby.js
// severity: 'mild' | 'moderate' | 'severe' | 'extreme'
// ============================================================
window.CURSES = [
  // ───────────────── MILD ─────────────────
  { id: 1,  name: "Four Eyes", severity: "mild", text: "You have naturally bad eyesight, needing glasses to see properly. Thankfully the curse comes with a single pair of prescription glasses. Lose them and you're nearly blind." },
  { id: 2,  name: "Perverted Aura", severity: "mild", text: "You radiate an aura of perversion and deviancy. People assume your intentions are lewd no matter how kind-hearted or saintly you actually are." },
  { id: 3,  name: "Milkaholic", severity: "mild", text: "You are addicted to milk. You NEED it. Go too long without and you suffer alcohol-style withdrawal regardless of any resistance or immunity." },
  { id: 4,  name: "Alcoholism", severity: "mild", text: "You just really like drinking. Every hour without alcohol gives you Disadvantage on INT and WIS saves until you drink." },
  { id: 5,  name: "Untitled Goose", severity: "mild", text: "You are haunted by the Untitled Goose, whose goal is to minorly inconvenience and harass you and everyone near you. Kill or trap it and it respawns in 10 seconds within 100m. It can teleport within 10m of you whenever unobserved." },
  { id: 6,  name: "Bad Blood", severity: "mild", text: "You were born into a family of bad people — criminals, cultists, crooks, gangsters, or god forbid, a corpo. Their reputation follows you." },
  { id: 7,  name: "Dramatic Lighting", severity: "mild", text: "Lighting around you is always inexplicably dramatic. Stealth checks in shadow are made at Disadvantage because a spotlight just finds you." },
  { id: 8,  name: "Permanent Hiccups", severity: "mild", text: "You have the hiccups. Forever. Disadvantage on Stealth and any check requiring you to be quiet." },
  { id: 9,  name: "Wet Socks", severity: "mild", text: "Your socks are always, inexplicably, damp. -5 ft speed and you are perpetually uncomfortable." },
  { id: 10, name: "Cursed Comic Sans", severity: "mild", text: "All text you write appears in Comic Sans to others, and no one takes any of your written communication seriously." },
  { id: 11, name: "Crittermagnet", severity: "mild", text: "Small animals — squirrels, pigeons, raccoons, cats — constantly swarm you. They're not hostile, just relentlessly present and noisy." },
  { id: 12, name: "Mondays", severity: "mild", text: "It is always, spiritually, a Monday for you. Disadvantage on your first roll of every combat." },
  { id: 13, name: "Sneezing Fits", severity: "mild", text: "You sneeze violently and uncontrollably whenever you try to be sneaky or cast something subtle. Roll a DC 12 CON save or your turn is wasted sneezing." },
  { id: 14, name: "The Floor Is Sticky", severity: "mild", text: "Every floor you walk on is slightly sticky. Difficult terrain on any surface that isn't bare earth." },
  { id: 15, name: "Verbal Tic", severity: "mild", text: "You must end every sentence with an embarrassing word of the DM's choosing, ttebayo. Failure to do so deals 1d4 psychic damage to you." },
  { id: 16, name: "Cursed Reflection", severity: "mild", text: "Your reflection moves a half-second behind you and occasionally makes rude gestures you didn't make. People find it deeply unsettling." },
  { id: 17, name: "Allergic to Money", severity: "mild", text: "You break out in hives when carrying more than 50 gold. Itchy, red, and very visible." },
  { id: 18, name: "Loud Chewer", severity: "mild", text: "You chew with cataclysmic volume. Impossible to eat discreetly; everyone within 30ft knows you're snacking." },
  { id: 19, name: "Eternal Bedhead", severity: "mild", text: "Your hair cannot be tamed by any means — magical, mundane, or divine. Disadvantage on Persuasion in formal settings." },
  { id: 20, name: "Backwards Day", severity: "mild", text: "Once per day at a random moment chosen by the DM, your movement controls reverse for one minute. Left is right, forward is back." },

  // ───────────────── MODERATE ─────────────────
  { id: 21, name: "Dead Tongues", severity: "moderate", text: "You can only speak in dead tongues that no one alive can understand. Writing still works, but conversation is impossible." },
  { id: 22, name: "Yandere", severity: "moderate", text: "Somewhere out there is a yandere yearning for your love who won't take no for an answer and will not listen to reason. They will find you." },
  { id: 23, name: "Taxation", severity: "moderate", text: "Only death and taxes are certain. The IRS seizes wealth they deem illegal. Roll 1d100: 1-20 lose ALL wealth. 21-40 lose 2/3. 41-60 lose 1/2. 61-85 lose 1/3. 86-100 they apologize, Senator." },
  { id: 24, name: "Hated by the FISH", severity: "moderate", text: "Every sea monster and aquatic creature in existence despises you specifically. Water travel is a death wish." },
  { id: 25, name: "Coin Flip Luck", severity: "moderate", text: "Before each combat, flip a coin. Heads: advantage on all rolls this fight. Tails: disadvantage on all rolls this fight. The DM flips." },
  { id: 26, name: "Glass Cannon", severity: "moderate", text: "Your max HP is halved, but your damage output is doubled. Live fast." },
  { id: 27, name: "Truth Compulsion", severity: "moderate", text: "You physically cannot lie. Every question asked of you must be answered with the complete, unfiltered truth." },
  { id: 28, name: "Magnetic Personality", severity: "moderate", text: "You are literally magnetic. Metal objects fly toward and stick to you. Wearing metal armor pins enemies' weapons to you; it's a mixed bag." },
  { id: 29, name: "Shrinking Violet", severity: "moderate", text: "Whenever someone compliments you, you physically shrink by 10%. Insults restore your size. You could vanish from praise alone." },
  { id: 30, name: "The Itch", severity: "moderate", text: "You have an unreachable, maddening itch in the center of your back. Every turn in combat, DC 13 WIS save or you spend your bonus action trying to scratch it." },
  { id: 31, name: "Doppelgänger Debt", severity: "moderate", text: "A doppelgänger has been ruining your reputation across the land, racking up debts and crimes in your name. Everyone you meet thinks they know you." },
  { id: 32, name: "Echo", severity: "moderate", text: "Everything you say is repeated loudly by a disembodied voice three seconds later. Stealth and secrecy become nearly impossible." },
  { id: 33, name: "Inverted Empathy", severity: "moderate", text: "You feel the opposite of what's appropriate — joy at funerals, grief at parties. Your reactions alienate everyone around you." },
  { id: 34, name: "Weight of the World", severity: "moderate", text: "Gravity affects you at 2x strength. -10 ft speed, Disadvantage on Acrobatics and jumps, and falling hurts twice as much." },
  { id: 35, name: "Compulsive Gambler", severity: "moderate", text: "You cannot pass up a wager. Any time someone offers a bet, you must accept it. DC 15 WIS save to resist, and you take it at Disadvantage." },
  { id: 36, name: "Touch of Decay", severity: "moderate", text: "Plants wither and food rots at your touch. Fresh provisions spoil in your pack; you can never enjoy a fresh meal again." },
  { id: 37, name: "Mimic's Mark", severity: "moderate", text: "Mimics are obsessed with you. Any container, chest, or door you approach has a chance of being a mimic that specifically wants YOU." },
  { id: 38, name: "Stage Fright", severity: "moderate", text: "Whenever three or more people watch you, you freeze. DC 14 CHA save at the start of your turn or you can only Dodge." },
  { id: 39, name: "The Tab", severity: "moderate", text: "You owe an enormous debt to a very patient, very dangerous loan shark. They send increasingly threatening collectors. The interest never stops." },
  { id: 40, name: "Misfortune Teller", severity: "moderate", text: "You can see minor glimpses of the future, but only bad ones, and only your own. You know something terrible is coming but never quite what." },
  { id: 41, name: "Salt Circle", severity: "moderate", text: "You cannot cross a line of salt. At all. Enemies who know this can trap you trivially with a handful of seasoning." },
  { id: 42, name: "Borrowed Time", severity: "moderate", text: "A ghostly clock floats above your head, visible to all, counting down to a time only the DM knows. It's unsettling and a constant distraction in social settings." },
  { id: 43, name: "Reverse Midas", severity: "moderate", text: "Valuable things you touch for too long turn to worthless lead. Hold a gem too long, it's slag. Grip your gold pouch too tight, it's a brick of nothing." },
  { id: 44, name: "Cursed Honesty Bell", severity: "moderate", text: "A small bell follows you and rings loudly every time you attempt deception, even a white lie. There is no muffling it." },
  { id: 45, name: "Allergic to Heroism", severity: "moderate", text: "Every time you perform a genuinely heroic act, you sneeze so hard you're knocked prone. The more heroic, the harder the fall." },
  { id: 46, name: "Split Personality", severity: "moderate", text: "An alternate personality surfaces at the worst moments. DC 13 WIS save when stressed or the DM controls you for one round." },
  { id: 47, name: "Perpetual Stranger", severity: "moderate", text: "People forget your name and face within minutes of meeting you. Building any lasting relationship is an uphill battle every single time." },
  { id: 48, name: "Bad Omen Aura", severity: "moderate", text: "Allies within 10 ft of you have Disadvantage on death saving throws. They'll want to keep their distance." },

  // ───────────────── SEVERE ─────────────────
  { id: 49, name: "Curse of Arms", severity: "severe", text: "You cannot wield weapons. The moment you try to hold or use one, it is ripped from your hands and you are shocked by lightning that intensifies with each attempt." },
  { id: 50, name: "Disarmed", severity: "severe", text: "You are missing an arm — left or right is a coin flip. In its place is a stub extending slightly past your shoulder. Permanent until removed by the DM." },
  { id: 51, name: "Overloading", severity: "severe", text: "Your energy regeneration never stops, even at max. Excess energy causes immense pain, injury, and a chance of permanent harm. You lose the ability to precisely control your energy at all." },
  { id: 52, name: "Fallen from Grace", severity: "severe", text: "Any roll below a 4 is treated as a Natural 1. The dice gods have forsaken you." },
  { id: 53, name: "Glass Bones", severity: "severe", text: "Your bones are brittle as glass. Any time you take bludgeoning damage, you also gain a level of exhaustion. Falling is potentially lethal." },
  { id: 54, name: "Mute Mage", severity: "severe", text: "You can no longer speak above a whisper, and any ability requiring a verbal/vocal component now requires a DC 15 check to push enough sound out." },
  { id: 55, name: "Marked Prey", severity: "severe", text: "A legendary hunter has marked you as their final trophy. They are always one step behind, always watching, and they never, ever give up." },
  { id: 56, name: "Energy Leech", severity: "severe", text: "Your maximum energy/aura/mana pool drains by 10% every long rest and does not return until the curse is lifted. Eventually you'll have nothing." },
  { id: 57, name: "Phantom Pain", severity: "severe", text: "You feel the pain of every wound your allies take as if it were your own. When an ally drops to 0 HP, you take 2d6 psychic damage." },
  { id: 58, name: "The Hunger", severity: "severe", text: "You must consume twice the normal food and water or gain exhaustion every few hours. In a famine or siege, this is a death sentence." },
  { id: 59, name: "Cursed Loyalty", severity: "severe", text: "You cannot attack or work against the first person who shows you genuine kindness after this curse takes hold, even if they become your enemy." },
  { id: 60, name: "Iron Lungs Inverted", severity: "severe", text: "You can only breathe underwater now. On dry land you are slowly suffocating — one level of exhaustion per hour out of water." },
  { id: 61, name: "Daywalker's Bane", severity: "severe", text: "Sunlight burns you. In direct sunlight you take 1d6 radiant damage per round and have Disadvantage on all rolls. The night is your only refuge." },
  { id: 62, name: "Shared Fate", severity: "severe", text: "Your life is magically bound to a random NPC chosen by the DM. If they die, you die. You don't know who they are." },
  { id: 63, name: "The Collector", severity: "severe", text: "An entity collects a piece of you each time you sleep — a memory, a skill, a name. Every long rest, lose something the DM chooses." },
  { id: 64, name: "Berserk Trigger", severity: "severe", text: "When you drop below half HP, you fly into an uncontrollable rage. The DM controls you and you attack the nearest creature — ally or enemy — until combat ends." },
  { id: 65, name: "Spell Backfire", severity: "severe", text: "Every ability you use has a 20% chance to target you instead of your intended target. Roll a d10 before each cast — 1-2 means it hits you." },
  { id: 66, name: "Walking Curse", severity: "severe", text: "Bad luck radiates from you. Every ally within 30 ft must roll a d20 at the start of their turn; on a 1, their action is wasted by sudden misfortune." },
  { id: 67, name: "The Doubt", severity: "severe", text: "A voice in your head convinces you that you'll fail. You must roll all attacks and saves twice and take the LOWER result for the next three sessions." },
  { id: 68, name: "Brittle Soul", severity: "severe", text: "You can no longer be healed by magic. Only natural rest restores your HP, and at half the normal rate." },
  { id: 69, name: "Vow of Poverty (Forced)", severity: "severe", text: "You cannot own more than what you can carry in two hands. Anything else slips away, is lost, stolen, or destroyed within a day." },
  { id: 70, name: "The Withering", severity: "severe", text: "You age one year every long rest. Your body weakens accordingly — eventually, time itself becomes the enemy you cannot fight." },

  // ───────────────── EXTREME ─────────────────
  { id: 71, name: "Leviathans", severity: "extreme", text: '"Detecting multiple Leviathan-class lifeforms in the region. Are you certain whatever you\'re doing is worth it?" Two Titans appear at a time of the DM\'s choosing. Each sends one devastating attack your way. Your goal: Survive.' },
  { id: 72, name: "Death's Bookmark", severity: "extreme", text: "Death has marked your page. The next time you would succeed on a death saving throw, you fail instead — once. You won't know which time it is." },
  { id: 73, name: "The Unraveling", severity: "extreme", text: "Reality forgets you exist a little more each day. Every long rest, one person who knew you forgets you entirely. Eventually, you were never here." },
  { id: 74, name: "Mirror World", severity: "extreme", text: "An evil version of you from a mirror dimension has crossed over and is hunting you to take your place. It has all your abilities and none of your mercy." },
  { id: 75, name: "Possessed", severity: "extreme", text: "A malevolent entity shares your body. Once per session at the DM's discretion, it seizes full control for an entire scene. You remember everything it does." },
  { id: 76, name: "The Price", severity: "extreme", text: "Every time you use your strongest ability, someone you've met dies somewhere in the world. The DM decides who. You will feel each one." },
  { id: 77, name: "Heart of Glass", severity: "extreme", text: "The next critical hit landed against you, no matter the source or your HP, drops you straight to 0. Live in fear of the crit." },
  { id: 78, name: "Eternal Pursuit", severity: "extreme", text: "An unkillable, relentless entity now exists for the sole purpose of ending you. It cannot be reasoned with, bargained with, or permanently stopped. It is always coming." },
  { id: 79, name: "Soul Debt", severity: "extreme", text: "You sold your soul (you don't remember when). The collector arrives within 3 sessions. Until then, every nat 20 you roll, you instead treat as a nat 1 — the contract demands its due." },
  { id: 80, name: "The Hollowing", severity: "extreme", text: "You are slowly becoming undead. Each long rest, lose 5 max HP permanently and one point of CON. When CON hits 0, you turn. There is no cure listed." },
  { id: 81, name: "World's Enemy", severity: "extreme", text: "Every faction, kingdom, guild, and god now considers you a top-priority threat. Bounties, assassins, and armies will come. You have no allies but your party." },
  { id: 82, name: "Time Skip", severity: "extreme", text: "At a random moment each session, you skip forward in time and lose your next full turn — frozen, vulnerable, and aware as the world moves without you." },
  { id: 83, name: "The Devourer", severity: "extreme", text: "Something is eating your abilities. Every long rest you permanently lose access to one skill, spell, or feature of the DM's choosing until you have nothing left." },

  // ───────────────── EXTRA / FUN ─────────────────
  { id: 84, name: "Anime Protagonist", severity: "moderate", text: "You must shout the name of every attack before using it, and monologue about the power of friendship for at least 6 seconds each combat. Failing to do so halves your damage." },
  { id: 85, name: "NPC Voice", severity: "mild", text: "You can now only speak in the third person about yourself, like a poorly-programmed video game NPC. 'This one greets you, traveler.'" },
  { id: 86, name: "Cursed Rizz", severity: "moderate", text: "Every attempt at charm or flirtation backfires catastrophically. Persuasion checks involving any romantic angle automatically fail and make things worse." },
  { id: 87, name: "Bottomless Pockets (Cursed)", severity: "moderate", text: "Anything you put in your pockets falls into an infinite void and is gone forever. You've lost so many things already." },
  { id: 88, name: "Laugh Track", severity: "mild", text: "An invisible studio audience laughs at your every failure and gasps at your every reveal. It's loud. It ruins all dramatic and stealthy moments." },
  { id: 89, name: "Sworn to the Bit", severity: "moderate", text: "You cannot break character on any joke or scheme, no matter how badly it's going. Once committed to a bit, you must see it through to the bitter end." },
  { id: 90, name: "Cursed Punctuality", severity: "mild", text: "You are physically incapable of being on time. You are always exactly 13 minutes late to everything, including combat — you act last in the first round, always." },
  { id: 91, name: "The Slav Squat", severity: "mild", text: "You can no longer sit in chairs. You may only squat. Formal events are agony and people stare." },
  { id: 92, name: "Main Character Syndrome", severity: "moderate", text: "You believe you are the only real person and everyone else is an extra. Disadvantage on all teamwork-based checks because you won't share the spotlight." },
  { id: 93, name: "Cursed Catchphrase", severity: "mild", text: "You have an embarrassing catchphrase you must say upon entering any room. The DM picks it. It never gets less embarrassing." },
  { id: 94, name: "Gravity's Plaything", severity: "severe", text: "Up and down switch for you at random intervals decided by the DM. You'll fall toward the ceiling without warning, then crash back down." },
  { id: 95, name: "Babel", severity: "severe", text: "Every language you hear sounds like a different language than it is, and everything you say comes out in a randomly chosen tongue. Communication is chaos." },
  { id: 96, name: "Cursed Crit", severity: "severe", text: "You can no longer roll a natural 20. Any d20 that lands on 20 is rerolled until it isn't. Greatness is forever just out of reach." },
  { id: 97, name: "The Understudy", severity: "moderate", text: "A wildly incompetent understudy occasionally replaces you mid-scene (DM's choice), played for maximum chaos, taking your turn in the worst way possible." },
  { id: 98, name: "Allergic to Plot", severity: "moderate", text: "Every time the party discovers crucial story information, you sneeze and forget it instantly. You will never know what's going on." },
  { id: 99, name: "Cursed Inventory", severity: "moderate", text: "One random item in your inventory transforms into a useless cursed object each long rest — your sword becomes a rubber chicken, your potion becomes hot sauce." },
  { id: 100, name: "The Final Boss Theme", severity: "mild", text: "Ominous boss music plays whenever you enter any room, terrifying shopkeepers and ruining every attempt at a peaceful interaction." },

  // ───────────────── BONUS CURSES (101+) ─────────────────
  { id: 101, name: "Cursed Sweet Tooth", severity: "mild", text: "You must consume something sugary every hour or take Disadvantage on your next roll. Dentists hate you." },
  { id: 102, name: "Two Left Feet", severity: "moderate", text: "You have, literally, two left feet now. -10 ft speed and Disadvantage on all Acrobatics and Athletics involving footwork." },
  { id: 103, name: "The Narrator Hates You", severity: "moderate", text: "An omniscient narrator describes all your actions in the most unflattering way possible, and the descriptions sometimes come true. The DM is the narrator." },
  { id: 104, name: "Cursed Crit Fail Magnet", severity: "severe", text: "Allies within 15 ft of you roll a d20 when they would crit; on a 10 or lower, it becomes a normal hit. Your bad luck is contagious." },
  { id: 105, name: "Eternal Intern", severity: "moderate", text: "The universe treats you as everyone's unpaid intern. NPCs constantly hand you menial tasks you feel compelled to complete (DC 13 WIS to refuse)." },
  { id: 106, name: "Lactose Revenant", severity: "moderate", text: "You are now violently lactose intolerant AND addicted to cheese. The cycle of suffering is eternal and entirely your own doing." },
  { id: 107, name: "Cursed GPS", severity: "moderate", text: "You have a perfect, unfailing sense of the exact wrong direction. You always know which way leads to danger, and you're compelled to second-guess into it." },
  { id: 108, name: "The Spotlight Thief", severity: "moderate", text: "Any time another player has a cool moment, you're compelled to try to one-up it (DC 14 WIS to resist), and you always fail embarrassingly." },
  { id: 109, name: "Cursed Immortality", severity: "extreme", text: "You cannot die — but you also cannot heal past 1 HP ever again. You will live forever, broken, in constant agony, unable to find rest." },
  { id: 110, name: "Schrödinger's Curse", severity: "extreme", text: "You have a curse AND you don't, until observed. Each session the DM secretly rolls; you might be fine, or you might be suffering any other curse on this list. You never know which until it triggers." },
];
