window.RWBY_DEFAULT_SHOP = [
  { category:'Dust — Crystals', name:'Fire Dust Crystal', price:500, desc:'Refined red crystal. Ignites on impact or channels through a weapon. SDC grade, post-embargo pricing.' },
  { category:'Dust — Crystals', name:'Ice Dust Crystal', price:500, desc:'Pale blue crystal. Freezes targets and surfaces, forms barriers of ice.' },
  { category:'Dust — Crystals', name:'Lightning Dust Crystal', price:520, desc:'Yellow crystal crackling with charge. Arcs between conductive targets.' },
  { category:'Dust — Crystals', name:'Wind Dust Crystal', price:480, desc:'Green crystal. Releases concussive gusts, propels gliding and leaping.' },
  { category:'Dust — Crystals', name:'Earth Dust Crystal', price:460, desc:'Brown crystal. Raises stone, hardens ground, shapes cover.' },
  { category:'Dust — Crystals', name:'Water Dust Crystal', price:470, desc:'Deep blue crystal. Conjures and controls water, pairs with Ice for sharp freezes.' },
  { category:'Dust — Crystals', name:'Gravity Dust Crystal', price:1400, desc:'Rare violet crystal. Alters local gravity for floating platforms or crushing slams. Severe shortage since the rail line attacks.' },
  { category:'Dust — Crystals', name:'Hard-Light Dust Crystal', price:1650, desc:'Rare prismatic crystal. Projects solid-light constructs and shields. Atlas-restricted, black-market priced.' },
  { category:'Dust — Crystals', name:'Steam Dust Crystal', price:680, desc:'Mixed Fire-and-Water crystal. Bursts of scalding pressure; favored for area control.' },
  { category:'Dust — Crystals', name:'Burn (Fire+Wind) Crystal', price:720, desc:'Combination crystal. Spreading flame carried on the wind.' },

  { category:'Dust — Vials & Powder', name:'Fire Dust Vial (powdered)', price:180, desc:'Loose red Dust for cartridge loading or pouches. Cheaper per use than crystal, less stable.' },
  { category:'Dust — Vials & Powder', name:'Ice Dust Vial (powdered)', price:180, desc:'Loose blue Dust. Common ammunition infusion.' },
  { category:'Dust — Vials & Powder', name:'Lightning Dust Vial (powdered)', price:190, desc:'Loose yellow Dust. Standard for ranged weapon charging.' },
  { category:'Dust — Vials & Powder', name:'Wind Dust Vial (powdered)', price:170, desc:'Loose green Dust. Mobility and knockback rounds.' },
  { category:'Dust — Vials & Powder', name:'Earth Dust Vial (powdered)', price:160, desc:'Loose brown Dust. Defensive and terrain rounds.' },
  { category:'Dust — Vials & Powder', name:'Gravity Dust Vial (powdered)', price:520, desc:'Loose violet Dust. Scarce; rationed by most reputable shops.' },
  { category:'Dust — Vials & Powder', name:'Mixed Dust Pouch (assorted)', price:220, desc:'A pouch of mismatched powdered Dust. Unreliable potency, budget option.' },

  { category:'Dust — Ammunition', name:'Dust Cartridges, Standard (×30)', price:120, desc:'Pre-loaded rounds infused with elemental Dust. Specify element on purchase.' },
  { category:'Dust — Ammunition', name:'Dust Cartridges, Heavy (×15)', price:160, desc:'High-caliber Dust rounds for cannon-class weapons.' },
  { category:'Dust — Ammunition', name:'Dust Shells, Shotgun (×20)', price:140, desc:'Scattershot Dust shells. Popular for melee-shift weapons.' },
  { category:'Dust — Ammunition', name:'Dust Rounds, Sniper (×10)', price:200, desc:'Precision-cut Dust rounds with stabilized burn.' },

  { category:'Weapons — Melee', name:'Combat Knife', price:80, desc:'1d4 piercing/slashing. Light, concealable, throwable.' },
  { category:'Weapons — Melee', name:'Short Sword', price:180, desc:'1d6 slashing. Reliable Huntsman trainee sidearm.' },
  { category:'Weapons — Melee', name:'Longsword', price:300, desc:'1d8 slashing, two-handed 1d10. Standard versatile blade.' },
  { category:'Weapons — Melee', name:'Greatsword', price:500, desc:'2d6 slashing, heavy, two-handed. Favored by power fighters.' },
  { category:'Weapons — Melee', name:'War Axe', price:340, desc:'1d8 slashing, brutal on a critical hit.' },
  { category:'Weapons — Melee', name:'Battle Spear', price:260, desc:'1d8 piercing, reach. Keeps Grimm at distance.' },
  { category:'Weapons — Melee', name:'War Hammer', price:420, desc:'2d6 bludgeoning, heavy. Stuns and shatters guard.' },
  { category:'Weapons — Melee', name:'Twin Daggers (pair)', price:240, desc:'1d4 each, light, dual-wield. Quick Semblance-paired strikes.' },
  { category:'Weapons — Melee', name:'Quarterstaff', price:60, desc:'1d6 bludgeoning, versatile 1d8. Cheap, dependable.' },

  { category:'Weapons — Ranged', name:'Light Pistol', price:280, desc:'1d8 piercing, 30/90 ft. Sidearm; chambers Dust cartridges.' },
  { category:'Weapons — Ranged', name:'Hunting Rifle', price:520, desc:'1d10 piercing, 80/240 ft. Bread-and-butter Huntsman ranged arm.' },
  { category:'Weapons — Ranged', name:'Combat Shotgun', price:480, desc:'2d6 at close range, 30/90 ft. Pairs with shift-weapons.' },
  { category:'Weapons — Ranged', name:'Sniper Rifle', price:900, desc:'2d10 piercing, 120/480 ft. High cost, high reach.' },
  { category:'Weapons — Ranged', name:'Recurve Bow', price:120, desc:'1d8 piercing, 150/600 ft. Silent; takes Dust-tipped arrows.' },
  { category:'Weapons — Ranged', name:'Hand Crossbow', price:160, desc:'1d6 piercing, light, 30/120 ft.' },

  { category:'Weapons — Mecha-Shift', name:'Mecha-Shift Frame (blank)', price:1200, desc:'A modular weapon chassis that transforms between two configured forms. Requires a smith to fit your blueprint.' },
  { category:'Weapons — Mecha-Shift', name:'Transformation Smithing (service)', price:850, desc:'A weaponsmith adds a second mecha-shift form to a weapon you already own.' },
  { category:'Weapons — Mecha-Shift', name:'Dust-Channeling Refit (service)', price:600, desc:'Upgrades a weapon to channel loaded Dust through its strikes or shots.' },

  { category:'Armor', name:'Reinforced Clothing', price:120, desc:'+1 AC. Light huntsman garb with woven plating. No stealth penalty.' },
  { category:'Armor', name:'Leather Combat Gear', price:200, desc:'Light armor, AC 11 + DEX. Flexible and quiet.' },
  { category:'Armor', name:'Studded Huntsman Vest', price:450, desc:'Light armor, AC 12 + DEX. Standard academy issue.' },
  { category:'Armor', name:'Chain Shirt', price:500, desc:'Medium armor, AC 13 + DEX (max 2). Worn under clothing.' },
  { category:'Armor', name:'Reinforced Breastplate', price:800, desc:'Medium armor, AC 14 + DEX (max 2). Atlas-forged steel.' },
  { category:'Armor', name:'Half-Plate', price:1500, desc:'Medium armor, AC 15 + DEX (max 2). Stealth disadvantage.' },
  { category:'Armor', name:'Full Plate', price:3000, desc:'Heavy armor, AC 18. Stealth disadvantage, STR 15 required.' },
  { category:'Armor', name:'Combat Shield', price:150, desc:'+2 AC. Some collapse into a gauntlet for shift-weapon users.' },
  { category:'Armor', name:'Dust-Weave Cloak', price:650, desc:'Resistant to one chosen Dust element; faint shimmer when triggered.' },

  { category:'Tools & Tech', name:'Scroll (standard)', price:400, desc:'The handheld communication and info device of Remnant. Calls, maps, Aura readouts, transformation triggers. Networked to the CCT.' },
  { category:'Tools & Tech', name:'Scroll (military-grade)', price:1100, desc:'Hardened Atlas Scroll with encrypted comms, deployable holo-display, and Aura-scanner ports.' },
  { category:'Tools & Tech', name:'First-Aid Med Kit', price:90, desc:'Bandages, salves, and a stim shot. Stabilizes a downed ally or restores a short rest of HP.' },
  { category:'Tools & Tech', name:'Field Surgery Kit', price:260, desc:'Advanced kit; grants advantage on Medicine checks and treats serious wounds.' },
  { category:'Tools & Tech', name:'Aura Stabilizer (single-use)', price:320, desc:'Injector that jump-starts a depleted Aura, restoring a small reserve once per use.' },
  { category:'Tools & Tech', name:'Dust Refining Kit', price:380, desc:'Portable tools to refine raw Dust into usable powder or recharge cartridges.' },
  { category:'Tools & Tech', name:'Grappling Hook & Line', price:75, desc:'50 ft line with a Dust-assisted retract. Climb, swing, or pull.' },
  { category:'Tools & Tech', name:'Climbing Kit', price:50, desc:'Pitons, harness, and rope for vertical terrain.' },
  { category:'Tools & Tech', name:'Survival Pack', price:110, desc:'Bedroll, rations (7 days), tinderbox, mess kit, waterskin, rope.' },
  { category:'Tools & Tech', name:'Binoculars (Dust-optic)', price:140, desc:'Long-range optics with low-light Dust enhancement.' },
  { category:'Tools & Tech', name:'Holo-Map Projector', price:230, desc:'Projects terrain and tactical overlays from Scroll data.' },
  { category:'Tools & Tech', name:'Lockpick Set', price:60, desc:'Quality picks for mechanical and simple electronic locks.' },
  { category:'Tools & Tech', name:'Flare Launcher (×6 flares)', price:85, desc:'Signal flares for distress, marking, or a brief blinding flash.' },
  { category:'Tools & Tech', name:'Portable Shield Generator', price:1300, desc:'Deploys a temporary Hard-Light barrier. Atlas tech, limited charges.' },

  { category:'Consumables', name:'Healing Tonic', price:130, desc:'Restores a modest amount of HP when drunk. Bitter, fast-acting.' },
  { category:'Consumables', name:'Stim Shot', price:180, desc:'Temporary surge of speed and resilience for one encounter.' },
  { category:'Consumables', name:'Antitoxin Vial', price:60, desc:'Advantage on saves against poison for one hour.' },
  { category:'Consumables', name:'Smoke Pellets (×5)', price:70, desc:'Throwable smoke for cover or escape.' },
  { category:'Consumables', name:'Ration Bars (×7)', price:35, desc:'A week of compact field rations.' },
  { category:'Consumables', name:'Aura Energy Drink', price:45, desc:'Minor Aura regen over a short rest. Tastes like burnt sugar.' },

  { category:'Services', name:'Weapon Maintenance', price:50, desc:'A smith cleans, sharpens, and tunes one weapon to peak condition.' },
  { category:'Services', name:'Armor Repair', price:80, desc:'Restores damaged armor to full protection.' },
  { category:'Services', name:'Dust Recharge (per weapon)', price:90, desc:'Tops off a weapon\u2019s built-in Dust reservoir.' },
  { category:'Services', name:'Bullhead Transport (one-way)', price:300, desc:'Airship passage to a kingdom or frontier outpost.' },
  { category:'Services', name:'Inn Stay (per night)', price:25, desc:'A bed, a hot meal, and a locked door between you and the night.' }
];
